---
spring:
  profiles: dev

server:
  port: 8761

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: aws

server:
  port: 8761

logging.level.com.netflix: INFO

eureka:
  environment: production
  instance:
    non-secure-port: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerDNSName: gr8conf.vpc
    eurekaServerPort: 8761
    eurekaServerURLContext: eureka
    useDnsForFetchingServiceUrls: true
  server:
    bindingStrategy: route53
    route53DomainTTL: 30


